id: P007984
initial_creation_type: ocr
source_metadata:
  id: bdr:W21621
  title: རྒྱལ་པོ་སྤྲིན་གྱི་བཞོན་པའི་རྟོགས་བརྗོད
  author: ''
  volumes:
    e9f94fd2cb07406f86be67f04cec8c89:
      image_group_id: I4751
      title: ''
      volume_number: 1
      total_pages: 143
ebook_metadata:
  title: རྒྱལ་པོ་སྤྲིན་གྱི་བཞོན་པའི་རྟོགས་བརྗོད
  author: ''
  sku: P007984
  cover: cover.jpg
  layers:
  - pagination
