id: P007984
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W21621
  title: རྒྱལ་པོ་སྤྲིན་གྱི་བཞོན་པའི་རྟོགས་བརྗོད
  author: ''
  volumes:
    e9f94fd2cb07406f86be67f04cec8c89:
      image_group_id: I4751
      title: ''
      volume_number: 1
      total_pages: 143
      base_file: v001.txt
